# |
# | WORD HISTORY
# | CONFIGURATION
# |
# |

# Hello, thank you for using WordHistory
# Here you can find the configurational aspects of this plugin

# If you ever need any asistance, I am available through spigot or discord (Perotin#3447)


